<a href="https://colab.research.google.com/github/hamza7771/Hamza_qureshi_quater2_assignment/blob/main/Credit_card_fraud_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
from google.colab import drive
drive.mount('/content/drive')



Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [11]:
cd /content/drive/MyDrive/ai_assignment/


/content/drive/MyDrive/ai_assignment


In [12]:
import pandas as pd
credit=pd.read_csv("./creditcard.csv")
import numpy as np
import tensorflow as tf


In [13]:
credit.shape

(284807, 31)

In [14]:
credit.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [15]:
#x=credit.Amount
#x.isnull().sum()
#np.where(credit.applymap(lambda x: x==" "))
#x.value_counts()

(credit['Amount'].values==0).sum()  #no of zeros in amount column

1825

In [16]:
(credit['Class'].values==1).sum()  #no of zeros in amount column

492

In [17]:
np.where(credit.Amount.apply(lambda x: x==0))


(array([   383,    514,    534, ..., 283949, 284085, 284770]),)

In [34]:
mean=train_data.mean(axis=0)
std=train_data.std(axis=0)
train_data-=mean
train_data/=std
test_data-=mean
test_data/=std

train_data.head()
#test_data.head()

mean_label=train_label.mean(axis=0)
std_label=train_label.std(axis=0)
train_label-=mean_label
#train_data.head(5)
train_label/=std_label
#print(mean)

#print(std)
test_label-=mean_label
#train_data.head(5)
test_label/=std_label
#test_label
#train_data.head()
#test_data.head()

In [36]:
non_fraud=credit[credit['Class']==0]
fraud=credit[credit['Class']==1]
len(fraud)
non_fraud=non_fraud.sample(2*fraud.shape[0])
data=fraud.append(non_fraud)
data=data.sample(frac=1)
x=data.drop(columns='Class')
y=data['Class']
y.head(10)

274897    0
11502     0
34307     0
44270     1
191690    1
150669    1
53794     1
44954     0
151807    1
15751     1
Name: Class, dtype: int64

In [37]:
#non_fraud.shape
data.shape

(1476, 31)

In [38]:
#credit = credit.sample(frac = 1)
from sklearn.model_selection import train_test_split
train_data,test_data,train_label,test_label=train_test_split(x,y,test_size=0.30,random_state=45)

#credit

In [39]:
#np.random.seed()
#msk=np.random.rand(len(credit)) <0.5

#train_total=credit[msk]
#test_total=credit[~msk]


#train_label=train_label.loc[:,"Class"]
#test_label=test_label.loc[:"Class"]

#test_data=test_data.drop(columns='Class')
#train_data=train_data.drop(columns='Class')
train_data.head()


Time        V1        V2  ...       V27       V28  Amount
208073  136958.0 -4.049867  3.855728  ... -0.031349  0.043090    2.29
209431  137556.0  1.993188  0.038049  ... -0.026897 -0.077017   42.20
121379   76172.0  1.293695 -1.904419  ...  0.092571  0.037589  104.45
258682  158768.0  1.857333 -0.654287  ... -0.027323 -0.036233   74.99
191130  129127.0  2.047071  0.528578  ...  0.014604  0.006116    1.00

[5 rows x 30 columns]

In [40]:
train_data.dtypes

Time      float64
V1        float64
V2        float64
V3        float64
V4        float64
V5        float64
V6        float64
V7        float64
V8        float64
V9        float64
V10       float64
V11       float64
V12       float64
V13       float64
V14       float64
V15       float64
V16       float64
V17       float64
V18       float64
V19       float64
V20       float64
V21       float64
V22       float64
V23       float64
V24       float64
V25       float64
V26       float64
V27       float64
V28       float64
Amount    float64
dtype: object

In [41]:
#x=(credit.loc[:,credit.columns!='Class'])
#y=(credit.loc[:,credit.columns =='Class'])


In [42]:
#from sklearn.model_selection import train_test_split
#x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=45)

In [51]:
from keras import models
from keras import layers
rk=models.Sequential()
rk.add(layers.Dense(10,activation='relu',input_shape=(train_data.shape[1],)))
rk.add(layers.Dropout(0.5))
rk.add(layers.Dense(8,activation='relu'))
rk.add(layers.Dropout(0.5))
rk.add(layers.Dense(6,activation='relu'))
rk.add(layers.Dropout(0.5))
rk.add(layers.Dense(1,activation='sigmoid'))
rk.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])


In [64]:
rk.fit(train_data,train_label,epochs=100,validation_split=0.28,validation_batch_size=15,validation_steps=10)

Epoch 1/100
24/24 [==============================] - 0s 8ms/step - loss: 0.6876 - accuracy: 0.6770 - val_loss: 0.6427 - val_accuracy: 0.6600
Epoch 2/100
24/24 [==============================] - 0s 4ms/step - loss: 0.6618 - accuracy: 0.6783 - val_loss: 0.6424 - val_accuracy: 0.6600
Epoch 3/100
24/24 [==============================] - 0s 4ms/step - loss: 0.6463 - accuracy: 0.6810 - val_loss: 0.6425 - val_accuracy: 0.6600
Epoch 4/100
24/24 [==============================] - 0s 4ms/step - loss: 0.7295 - accuracy: 0.6810 - val_loss: 0.6424 - val_accuracy: 0.6600
Epoch 5/100
24/24 [==============================] - 0s 4ms/step - loss: 0.7055 - accuracy: 0.6797 - val_loss: 0.6421 - val_accuracy: 0.6600
Epoch 6/100
24/24 [==============================] - 0s 4ms/step - loss: 0.6338 - accuracy: 0.6797 - val_loss: 0.6420 - val_accuracy: 0.6600
Epoch 7/100
24/24 [==============================] - 0s 4ms/step - loss: 0.7032 - accuracy: 0.6797 - val_loss: 0.6419 - val_accuracy: 0.6600
Epoch 8/100
2

In [65]:
rk.evaluate(test_data,test_label)

14/14 [==============================] - 0s 1ms/step - loss: 0.6559 - accuracy: 0.6411


[0.6558799743652344, 0.6410835385322571]

In [66]:
rk.predict(np.array(test_data.iloc[1,:]).reshape(1,test_data.shape[1]))

array([[0.32316145]], dtype=float32)

In [67]:
pa=rk.predict(test_data)

In [70]:
pa


array([[0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.32316145],
       [0.323

array([0.39299047], dtype=float32)